name: Submit Stormtrooper Verification
on:
  workflow_dispatch:
    inputs:
      username:
        description: "CTF Username"
        required: true
      verificationCode:
        description: "Stormtrooper Verification Code"
        required: true
jobs:
  verify:
    name: Submit Stormtrooper Verification
    runs-on: ubuntu-latest
    steps:
      - name: Check fork
        if: github.event.repository.fork == false
        run: |
          echo "This workflow must run on your fork"
          exit 1

      - name: Mask Input
        id: add_mask
        run: |
          VERIFICATION_CODE=$(jq -r '.inputs.verificationCode' $GITHUB_EVENT_PATH)
          echo ::add-mask::$VERIFICATION_CODE
          echo SECRET_CODE="$VERIFICATION_CODE" >> $GITHUB_ENV

      - name: Submit Verification Request
        id: stormtrooper-verification
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://ctf.johnwduprey.com/github/"
          method: "POST"
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: "username=${{ inputs.username }}&verificationCode=${{ env.SECRET_CODE }}&ghuser=${{ github.event.sender.login }}"

      - name: Submission Response
        run: |
          echo ${{ steps.stormtrooper-verification.outputs.response }} >> $GITHUB_STEP_SUMMARY
